name: Deploy Website to Production
on:
  push:
    branches:
      - master
jobs:
  rsync_to_server:
    name: rsync_to_server
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Rsync Code to Remote
        run: |
          mkdir -p ~/.ssh/
          echo "$SSH_PRIVATE_KEY" > ../private.key
          sudo chmod 600 ../private.key
          echo "$SSH_KNOWN_HOSTS" > ~/.ssh/known_hosts
          rsync -rtvzPe "ssh -i $SSH_KEY_PATH" --delete --exclude .git ./ root@nolanmcmahon.net:/var/www/rcec/
        shell: bash
        env:
          SSH_PRIVATE_KEY: ${{secrets.SSH_PRIVATE_KEY}}
          SSH_KNOWN_HOSTS: ${{secrets.SSH_KNOWN_HOSTS}}
          SSH_KEY_PATH: ${{ github.workspace }}/../private.key
